############################################################
#
# article 静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@120.48.127.193:27017
      database: news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 114.115.141.225
    port: 5672
    username: admin
    password: 139900753
    virtual-host: imooc-news-dev
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.141.225:8848
        ip: 114.115.141.225
    sentinel:
      transport:
        dashboard: 120.48.127.193:8080   # 控制台的地址
        port: 8723
        clientIp: 114.115.141.225
# 定义freemarker生成的html位置
freemarker:
  html:
    target: /workspace/freemarker_html
    article: /usr/local/apache-tomcat-8.5.82/webapps/imooc-news-04/portal/a


