server:
  port: 8002

spring:
  redis:
    timeout: 5000
    database: 0
    #    host: 114.115.141.225
    #    port: 7000
    cluster:
      nodes:
        - 120.48.127.193:7000
        - 120.48.127.193:7001
        - 114.115.141.225:7000
        - 114.115.141.225:7001
        - 120.48.127.173:7000
        - 120.48.127.173:7001
      max-redirects: 3
    password: 139900753
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: localhost

