server:
  port: 8005

spring:
  redis:
    timeout: 5000
    database: 0
    cluster:
      nodes:
        - 120.48.127.193:7000
        - 120.48.127.193:7001
        - 114.115.141.225:7000
        - 114.115.141.225:7001
        - 120.48.127.173:7000
        - 120.48.127.173:7001
      max-redirects: 3
    password: 139900753
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: localhost