############################################################
#
# 搜索服务
# web访问端口号  约定：8006
#
############################################################
server:
  port: 8006
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: service-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300


