############################################################
#
# article微服务
# web访问端口号  约定：8001
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article
  datasource:                                         # 数据源的相关配置
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: "jdbc:mysql://120.48.127.193:3306/news01?useSSL=false&useUnicode=true&acharacterEncoding=utf-8&serverTimezone=Asia/Shanghai"
      username: master
      password: "139900753"
    slave:
      jdbc-url: "jdbc:mysql://114.115.141.225:3306/news01?useSSL=false&useUnicode=true&acharacterEncoding=utf-8&serverTimezone=Asia/Shanghai"
      username: root
      password: "139900753"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@120.48.127.193:27017
      database: news
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 120.48.127.193:9300
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 114.115.141.225
    port: 5672
    username: admin
    password: 139900753
    virtual-host: imooc-news-dev
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.141.225:8848
#        ip: 114.115.141.225
    sentinel:
      transport:
        eager: true # 是否饥饿加载。默认为 false 关闭
        dashboard: 120.48.127.193:8080   # 控制台的地址
        port: 8721
#        clientIp: 114.115.141.225
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.imooc.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true


# 定义freemarker生成的html位置
freemarker:
  html:
    target: /workspace/freemarker_html
    article: D:\Java\apache-tomcat-9.0.62\webapps\imooc-news-04\portal\a
#    article: /usr/local/apache-tomcat-8.5.82/webapps/imooc-news-04/portal/a
ribbon:
  ConnectTimeout: 5000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 5000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  MaxAutoRetries: 1             # 最大重试次数
  MaxAutoRetriesNextServer: 2   # 切换到下个微服务实例的重试次数
  # 当请求到某个微服务5s，超时后会进行重试，先重试连接自己当前的这个实例
  # 如果当前重试失败1次，则会切换到访问集群中的下一个微服务实例，切换最大为2次

logging:
  level:
    com.imooc.api.controller.user.UserControllerApi: debug
#    root: debug

# 配置feign
feign:
  client:
    config:
      # 配置服务提供方的名称
      service-user:
        loggerLevel: FULL
