############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-user
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: "jdbc:mysql://120.48.127.193:3306/news01?useSSL=false&useUnicode=true&acharacterEncoding=utf-8&serverTimezone=Asia/Shanghai"
      username: master
      password: "139900753"
    slave:
      jdbc-url: "jdbc:mysql://114.115.141.225:3306/news01?useSSL=false&useUnicode=true&acharacterEncoding=utf-8&serverTimezone=Asia/Shanghai"
      username: root
      password: "139900753"
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.141.225:8848
        ip: 114.115.141.225
    sentinel:
      transport:
        dashboard: 120.48.127.193:8080   # 控制台的地址
        port: 8719
        clientIp: 114.115.141.225
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 114.115.141.225
    port: 5672
    username: admin
    password: 139900753
    virtual-host: imooc-news-dev
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 120.48.127.193:9300

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.imooc.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
