server:
  port: ${port:8003}

spring:
  redis:
    timeout: 5000
    database: 0
    cluster:
      nodes:
        - 192.168.0.1:7000
        - 192.168.0.1:7001
        - 192.168.0.2:7000
        - 192.168.0.2:7001
        - 192.168.0.3:7000
        - 192.168.0.3:7001
      max-redirects: 3
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: localhost
